#!/bin/sh
###############################################################################
# ceerious i3 status config
# see "man i3status" for documentation.
#
# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!
###############################################################################

general {
    interval         = 2
    colors         = true
    color_good      = '#BBFF88'
    color_degraded  = '#F0B040'
    color_bad       = '#E04030'
}

order += "wireless _first_"
order += "ethernet _first_"
order += "disk /"
order += "cpu_usage"
order += "volume master"
order += "tztime local"

wireless _first_ {
    format_up = " %essid :%quality"
    format_down = ""
}

ethernet _first_ {
    # if you use %speed, i3status requires root privileges
    format_up = " %ip (%speed)"
    format_down = ""
}

cpu_usage {
    format = " %usage"
}

disk "/" {
    format = " %avail"
    prefix_type    = custom
    low_threshold = 30
    threshold_type = percentage_avail
}

disk "/media/win" {
    format = " %avail"
    prefix_type    = custom
    low_threshold = 20
    threshold_type = percentage_avail
}

volume master {
    format = "%volume"
    format_muted = " %volume"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

tztime local {
    format = "%a %d/%m/%y  %H:%M  "
}
